### ISSUE TITLE
Using reli-prof with Apache

### ISSUE THREAD

**Issue by PaiseHIM** [sj-i/php-profiler#277]
Hi, I am trying to use  reli-prof to profile PHP systems that runs on Apache, but can't get it working, 
I can connect to a PHP (stand alone) process  but ,I cant connect to  PHP process that is running on Apache.

I use the below cmd, but it does not return any response  (just a flashing prompt), any guidance will be much appreciated.   

sudo ./reli i:trace -p 1338

Current system process and versions.
ps -fu www-data
UID          PID    PPID  C STIME TTY          TIME CMD
www-data    1453    1098  0 Jul21 ?        00:00:00 php-fpm: pool www
www-data    1454    1098  0 Jul21 ?        00:00:00 php-fpm: pool www
www-data  739158    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  739161    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  739162    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  739164    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  740232    1338  0 00:06 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  834966    1338  0 09:05 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  834967    1338  0 09:05 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  848266    1338  0 10:20 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  929187    1338  0 17:42 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  929188    1338  0 17:42 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  929308    1338  0 17:43 ?        00:00:00 /usr/sbin/apache2 -k start
derek@mad:~$ ps -f | grep 1338
derek     933709  933473  0 18:09 pts/2    00:00:00 grep --color=auto 1338
derek@mad:~$ ps -fe | grep 1338
root        1338       1  0 Jul21 ?        00:00:12 /usr/sbin/apache2 -k start
www-data  739158    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  739161    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  739162    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  739164    1338  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  740232    1338  0 00:06 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  834966    1338  0 09:05 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  834967    1338  0 09:05 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  848266    1338  0 10:20 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  929187    1338  0 17:42 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  929188    1338  0 17:42 ?        00:00:00 /usr/sbin/apache2 -k start
www-data  929308    1338  0 17:43 ?        00:00:00 /usr/sbin/apache2 -k start
derek     933746  933473  0 18:09 pts/2    00:00:00 grep --color=auto 1338

derek@mad:~$ apache2 -version
Server version: Apache/2.4.57 (Ubuntu)
Server built:   2023-04-08T12:56:02

derek@mad:~$ php -version
PHP 8.2.8 (cli) (built: Jul  8 2023 07:10:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

**Comment by sj-i** [comment]
@PaiseHIM 
Hi!

> sudo ./reli i:trace -p 1338
> root 1338 1 0 Jul21 ? 00:00:12 /usr/sbin/apache2 -k start
> www-data 1453 1098 0 Jul21 ? 00:00:00 php-fpm: pool www
> www-data 739158 1338 0 00:00 ? 00:00:00 /usr/sbin/apache2 -k start
> www-data 739161 1338 0 00:00 ? 00:00:00 /usr/sbin/apache2 -k start

You are attaching reli to the master process of Apache.
If you use mod_php, the PHP VM is living in each Apache worker process.
If you use php-fpm, the PHP VM is living in each FPM worker process.
Whichever you are using, reli needs to be attached to the worker process where the VM used lives in.

```
sudo ./reli i:trace -p 739158
sudo ./reli i:trace -p 1454
```


Or, you may want to attach to multiple workers at the same time.
Then the daemon mode is there for you.

If you use fpm:

```
sudo ./reli i:daemon -P "^php fpm: pool www"
```

If you use mod_php:

```
sudo ./reli i:daemon -P "^/usr/sbin/apache2 -k start"
```

**Comment by PaiseHIM** [comment]
Hi, Good morning, Thanks for the response.

As per the Apache config we using  Apache forwarding to FPM.

So I tried " sudo ./reli i:daemon -P "^php fpm: pool www"" with no response (output).

Seeing FPM is run in a listener (root process) and handler (thread process) how do you know which thread is handling the request seeing there is 2 threads, when you run the above cmd? 

ps -fe | grep php
root        1098       1  0 Jul21 ?        00:00:18 php-fpm: master process (/etc/php/8.1/fpm/php-fpm.conf)
www-data    1453    1098  0 Jul21 ?        00:00:00 php-fpm: pool www
www-data    1454    1098  0 Jul21 ?        00:00:00 php-fpm: pool www

**Comment by sj-i** [comment]
@PaiseHIM
Oops, I told you a wrong option. There was a typo. Can you try this?

```
sudo ./reli i:daemon -P "^php-fpm: pool www"
```


The daemon mode of reli uses 8 worker processes by default, and each can be attached to a different target process. So your both fpm workers should be covered without problems.

The regex given to the -P option is used for seaching target processes containing PHP VM. So the regex should be matched to your commands of FPM workers.

**Comment by PaiseHIM** [comment]
Cool, I am Derek, by the way.

Still does the same (prompt with no output)

cmd I used
/var/www/html/hms2/profiler/vendor/bin$ sudo ./reli i:daemon -P "^php-fpm: pool www"

FPM Process
ps -fe | grep php
root        1098       1  0 Jul21 ?        00:00:18 php-fpm: master process (/etc/php/8.1/fpm/php-fpm.conf)
www-data    1453    1098  0 Jul21 ?        00:00:00 php-fpm: pool www
www-data    1454    1098  0 Jul21 ?        00:00:00 php-fpm: pool www

**Comment by sj-i** [comment]
@PaiseHIM 

Hmm, then Derek, can you give me the output of this command?

```
sudo head /proc/1453/maps
```

**Comment by PaiseHIM** [comment]
sudo head /proc/1453/maps
[sudo] password for derek: 
40776000-48776000 rw-s 00000000 00:01 11                                 /dev/zero (deleted)
565210a85000-565210b5f000 r--p 00000000 08:01 18097                      /usr/sbin/php-fpm8.1
565210b5f000-565210e5d000 r-xp 000da000 08:01 18097                      /usr/sbin/php-fpm8.1
565210e5d000-565210f3f000 r--p 003d8000 08:01 18097                      /usr/sbin/php-fpm8.1
565210f40000-565210fcd000 r--p 004ba000 08:01 18097                      /usr/sbin/php-fpm8.1
565210fcd000-565210fcf000 rw-p 00547000 08:01 18097                      /usr/sbin/php-fpm8.1
565210fcf000-565210fee000 rw-p 00000000 00:00 0 
565211dba000-565212157000 rw-p 00000000 00:00 0                          [heap]
565212157000-565212179000 rw-p 00000000 00:00 0                          [heap]
7f99d5ec1000-7f99d5ec7000 r--p 00000000 08:01 1210                       /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2

**Comment by sj-i** [comment]
@PaiseHIM 

Ah, then this may work.

```
sudo ./reli i:daemon --php-regex="php-fpm" -P "^php-fpm: pool www"
```

Currently, reli searches the binary of the interpreter from the loaded modules of the target process by using the following default regex.

```
.*/(php(74|7\.4|80|8\.0|81|8\.1|82|8\.2)?|php-fpm|libphp[78]?.*\.so)$
```

So `php-fpm8.1` doesn't match, because the name of the binary doesn't end with php-fpm. `--php-regex` is used to override the default regex.

Can you tell me how you install the FPM binary?
If it's an usual way of a distribution, I should update the default regex on the next release.

**Comment by PaiseHIM** [comment]
Still does the same.

/var/www/html/hms2/profiler/vendor/bin$ sudo ./reli i:daemon --php-regex="php-fpm" -P "^php-fpm: pool www"
[sudo] password for derek: 

We  running Ubuntu on Azure in a VM, I have not done the installation my self, I will assume its done through apt-get.  

OS info
uname -a
Linux mad 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/issue
Ubuntu 22.04.2 LTS \n \l

**Comment by sj-i** [comment]
@PaiseHIM 

Hmm...  seems to be working on my end, I tried it now on Ubuntu 23.04 with the FPM binary installed via apt.

If you have time, can you tell me what you see in reli.log when you change this line in the config file to `LogLevel::DEBUG` and run it?
https://github.com/reliforp/reli-prof/blob/0b771a94c912fc35a739dd63cb378e3186a1e509/config/config.php#L21

You probably installed reli with composer require, not with composer create-project, so you should have the config file in the following path.
```
/var/www/html/hms2/profiler/vendor/reliforp/reli-prof/config/config.php 
```

reli.log will be generated to the working directory on execution. So if you are in `/var/www/html/hms2/profiler/vendor/bin`, then the log would be outputted to there.

**Comment by PaiseHIM** [comment]
Hi, Good Morning, Thanks for the help so far, please find the zipped log file attached.
[reli.log.zip](https://github.com/reliforp/reli-prof/files/12169237/reli.log.zip)

**Comment by PaiseHIM** [comment]
Hi, after seeing the log output and not seeing any errors, I tried mod_php option which worked. So it looks like we have a config problem with FPM, I will ask the team about it. (I am just a contracter)

What is the unit of measure  for the time interval, written to log?

[Output_27072023.txt](https://github.com/reliforp/reli-prof/files/12171390/Output_27072023.txt)

**Comment by PaiseHIM** [comment]
Thanks for the help and all the effort you put in for writing and maintaining reli-prof, enjoy your day.

**Comment by sj-i** [comment]
@PaiseHIM 

Thanks for the log!

And congrats on finding out that you are using mod_php :)

The default sampling interval is 10ms. You can change it via `-s` or `--sleep-ns` in nanoseconds. Of course, it is not possible to reflect nanosecond specifications accurately, so I personally recommend specifying an interval of at least 1 millisecond (1000000ns) or more. 

FYI, a retrieval of 1 trace often takes around 100 microseconds on my machine, with JIT enabled.

I think we've solved the problem, so I'll close this issue. Thanks!
