### ISSUE TITLE
Not every request gets profiled / saved to output

### ISSUE THREAD

**Issue by lighthuter** [sj-i/php-profiler#407]
Hello, I noticed a strange behaviour when using output to file (-o option). Roughly, only every second request gets written in the output file. Is there a way to fix it?

**Comment by lighthuter** [comment]
I've checked it further, it seems this behaviour is reproducible regardless of whether `-o` option is provided.

**Comment by sj-i** [comment]
@lighthuter 
Hi!

This isn't reproducible on my end. Has the issue been resolved?
